Master
diopmo399/confino pull request #2
Opened 2020-11-13 13:19 UTC by diopmo399

2020-11-15 18:10 UTC, wariored requested changes

2020-11-15 18:10 UTC, wariored commented on confino-front/src/App.css
> +.App-header {
le nom des class html doivent commencer par une lettre minuscule

2020-11-15 18:10 UTC, wariored commented on pom.xml
> +        <!--<dependency>-->
supprime ce commentaire. On supprime toujours les commentaires des code

2020-11-15 18:10 UTC, wariored commented on src/main/java/io/work/confino/config/WebSecurityConfig.java
> +        // jsr250Enabled = true,
à supprimer

2020-11-15 18:10 UTC, wariored commented on src/main/java/io/work/confino/controller/CompanyController.java
> +        companyService.deleteCompany(id);
Que se passe t-il si l'id n'existe pas?
Dans ce cas, retourne un NotFound

2020-11-15 18:10 UTC, wariored commented on src/main/java/io/work/confino/controller/JobController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(jobService.saveJob(job));
essaies de catcher les erreurs et de retourner les status correspondants comme le ferait une API Rest. Sinon on aura un InternalServerError

2020-11-15 18:10 UTC, wariored commented on src/main/java/io/work/confino/controller/JobController.java
> +        return ResponseEntity.ok(id);
pareil ici

2020-11-15 18:10 UTC, wariored commented on src/main/java/io/work/confino/exceptionHandler/GlobalExceptionHandler.java
> +       return  new ApiResponse(404,ex.getMessage(),null);
indentation

2020-11-15 18:10 UTC, wariored commented on src/main/java/io/work/confino/exceptions/ExceptionHandlingController.java
> +    /*@ExceptionHandler(MissingServletRequestParameterException.class)
à supprimer

2020-11-15 18:10 UTC, wariored commented on src/main/java/io/work/confino/exceptions/ExceptionMessage.java
> +public class ExceptionMessage {
pourquoi elle ne extends pas la classe Exception?

2020-11-15 18:10 UTC, wariored commented on src/test/java/io/work/confino/serviceTest/TestCandidateService.java
> +import io.work.confino.utilsTest.VARIABLES;
donnes un autre nom que VARIABLES,
Maybe: TestHelper

2020-11-15 18:10 UTC, wariored commented on src/test/java/io/work/confino/utilsTest/VARIABLES.java
>  package io.work.confino.utilsTest;
change le nom de ce fichier. VARIABLES.java n'est pas Adequat

2020-11-17 15:19 UTC, diopmo399 commented on src/main/java/io/work/confino/exceptions/ExceptionMessage.java
> +public class ExceptionMessage {
c'est pas la peine car cette classe permet juste de contruire le message qui doit etre envoyer aux clients

2020-11-17 15:19 UTC, diopmo399 commented on src/test/java/io/work/confino/serviceTest/TestCandidateService.java
> +import io.work.confino.utilsTest.VARIABLES;
OK inchallah

2020-11-17 15:19 UTC, diopmo399 commented on src/test/java/io/work/confino/utilsTest/VARIABLES.java
>  package io.work.confino.utilsTest;
ok

2020-11-17 15:26 UTC, diopmo399 commented on src/main/java/io/work/confino/controller/JobController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(jobService.saveJob(job));
je comprends pas le fait qu'il renvoi un internal serveur erreur

2020-11-27 12:29 UTC, merged